# -*- coding: utf-8 -*-
"""Predicting Road Accidents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGC_HXLQtDOvKtdrLJaHJtpruMsF7tCQ
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

train_df = pd.read_csv('/content/drive/MyDrive/playground-series-s5e10/train.csv')
test_df  = pd.read_csv('/content/drive/MyDrive/playground-series-s5e10/test.csv')

train_df.head()

train_df.info()

test_df.info()

print(train_df.isnull().sum())

print(test_df.isnull().sum())

"""DATA CLEANING"""

num_cols = train_df.select_dtypes(include=['int64','float64']).columns.tolist()
num_cols = [c for c in num_cols if c not in ['id','accident_risk']]
cat_cols = train_df.select_dtypes(include=['object','category']).columns.tolist()
cat_cols = [c for c in cat_cols if c != 'id']

# ── 1. Fill missing values ───────────────────────────────────────────
for col in num_cols:
    median = train_df[col].median()              # learn from train only
    train_df[col] = train_df[col].fillna(median)
    if col in test_df.columns:
        test_df[col] = test_df[col].fillna(median)  # apply same to test

for col in cat_cols:
    mode = train_df[col].mode()[0]               # learn from train only
    train_df[col] = train_df[col].fillna(mode)
    if col in test_df.columns:
        test_df[col] = test_df[col].fillna(mode)

# ── 2. Remove duplicates (train only) ───────────────────────────────
before = train_df.shape[0]
train_df = train_df.drop_duplicates()
after  = train_df.shape[0]
print(f"Duplicates removed: {before - after}")

# ── 3. Convert categoricals to category dtype ────────────────────────
for col in cat_cols:
    train_df[col] = train_df[col].astype('category')
    if col in test_df.columns:
        test_df[col] = test_df[col].astype('category')

# ── 4. Drop id columns ───────────────────────────────────────────────
train_df = train_df.drop(columns=['id'])
test_df  = test_df.drop(columns=['id'])

# ── Re-extract y after duplicate removal ────────────────────────────
y = train_df['accident_risk']

print("✅ Cleaning done")
print(f"Train shape: {train_df.shape}")
print(f"Test shape:  {test_df.shape}")

fig, axes = plt.subplots(3, 3, figsize=(18, 14))
fig.suptitle('Data Cleaning Verification', fontsize=16, fontweight='bold', y=1.02)

# ── 1. Missing values (should be all zero after cleaning) ────────────
ax = axes[0, 0]
missing = train_df.isnull().sum()
colors  = ['red' if v > 0 else 'green' for v in missing]
missing.plot(kind='bar', ax=ax, color=colors)
ax.set_title('Missing Values After Cleaning\n(all green = good ✅)')
ax.set_ylabel('Count')
ax.tick_params(axis='x', rotation=45)
ax.axhline(0, color='black', linewidth=0.8)

# ── 2. Data types distribution ───────────────────────────────────────
ax = axes[0, 1]
dtype_counts = train_df.dtypes.astype(str).value_counts()
dtype_counts.plot(kind='bar', ax=ax, color='steelblue')
ax.set_title('Column Data Types')
ax.set_ylabel('Number of columns')
ax.tick_params(axis='x', rotation=0)

# ── 3. Target distribution ───────────────────────────────────────────
ax = axes[0, 2]
y.value_counts().plot(kind='bar', ax=ax, color=['steelblue','coral'])
ax.set_title('Target Distribution\n(accident_risk values)')
ax.set_ylabel('Count')
ax.tick_params(axis='x', rotation=0)

# ── 4. Numeric column distributions ─────────────────────────────────
for i, col in enumerate(num_cols[:3]):   # plot first 3 numeric cols
    ax = axes[1, i]
    sns.histplot(train_df[col], bins=40, kde=True, ax=ax, color='steelblue')
    ax.set_title(f'{col} distribution')
    ax.set_ylabel('Count')

# ── 5. Categorical column distributions ─────────────────────────────
for i, col in enumerate(cat_cols[:3]):   # plot first 3 cat cols
    ax = axes[2, i]
    counts = train_df[col].value_counts()
    counts.plot(kind='bar', ax=ax, color='darkorange')
    ax.set_title(f'{col} value counts')
    ax.set_ylabel('Count')
    ax.tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

print("=" * 45)
print("       CLEANING VERIFICATION REPORT")
print("=" * 45)

# Missing values
total_missing_train = train_df.isnull().sum().sum()
total_missing_test  = test_df.isnull().sum().sum()
print(f"\n✅ Missing values in train: {total_missing_train}")
print(f"✅ Missing values in test:  {total_missing_test}")

# Duplicates
print(f"✅ Duplicates removed:      {before - after}")
print(f"✅ Train rows remaining:    {train_df.shape[0]}")

# Dtypes
print(f"\n✅ Column types in train:")
dtype_groups = train_df.dtypes.astype(str).groupby(train_df.dtypes.astype(str))
for dtype, cols in train_df.dtypes.astype(str).groupby(train_df.dtypes.astype(str)):
    col_list = train_df.columns[train_df.dtypes.astype(str) == dtype].tolist()
    print(f"   {str(dtype):15} → {col_list}")
# Shape match
train_cols = set(train_df.columns) - {'accident_risk'}
test_cols  = set(test_df.columns)
extra_train = train_cols - test_cols
extra_test  = test_cols  - train_cols
print(f"\n✅ Columns in train not in test: {extra_train or 'None'}")
print(f"✅ Columns in test not in train: {extra_test  or 'None'}")

# Target check
print(f"\n✅ Target (y) unique values: {y.unique()}")
print(f"✅ Target zeros: {(y==0).sum()} | ones: {(y==1).sum()}")
print("\n" + "=" * 45)
print("All checks passed — ready for encoding ✅")
print("=" * 45)

from sklearn.preprocessing import LabelEncoder

# ── Separate target ──────────────────────────────────────────────────
X = train_df.drop(columns=['accident_risk'])
y = train_df['accident_risk']

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"Target  — zeros: {(y==0).sum()} | ones: {(y==1).sum()}")

# ── Identify column types ────────────────────────────────────────────
numeric_cols     = X.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object','category']).columns.tolist()

print(f"\nNumeric columns    ({len(numeric_cols)}):     {numeric_cols}")
print(f"Categorical columns ({len(categorical_cols)}): {categorical_cols}")

# ── Label encode categoricals ────────────────────────────────────────
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()

    # Fit on train
    X[col] = le.fit_transform(X[col].astype(str))

    # Apply same encoder to test
    # Handle unseen categories gracefully
    test_df[col] = test_df[col].astype(str).apply(
        lambda x: x if x in le.classes_ else le.classes_[0]
    )
    test_df[col] = le.transform(test_df[col])

    label_encoders[col] = le
    print(f"  Encoded '{col}': {list(le.classes_)}")

print("\n✅ Label Encoding Done")
print(f"X shape after encoding:    {X.shape}")
print(f"test_df shape after encoding: {test_df.shape}")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Feature Encoding Verification', fontsize=15, fontweight='bold')

# ── 1. Numeric columns distribution ─────────────────────────────────
for i, col in enumerate(numeric_cols[:3]):
    ax = axes[0, i]
    sns.histplot(X[col], bins=40, kde=True, ax=ax, color='steelblue')
    ax.set_title(f'Numeric: {col}')
    ax.set_xlabel('Value')
    ax.set_ylabel('Count')

# ── 2. Categorical columns AFTER encoding ────────────────────────────
for i, col in enumerate(categorical_cols[:3]):
    ax = axes[1, i]
    counts = X[col].value_counts().sort_index()

    # Map encoded numbers back to original labels for readability
    le        = label_encoders[col]
    new_index = [le.classes_[j] for j in counts.index]
    counts.index = new_index

    counts.plot(kind='bar', ax=ax, color='darkorange', edgecolor='white')
    ax.set_title(f'Categorical (encoded): {col}')
    ax.set_ylabel('Count')
    ax.tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

print("      ENCODING VERIFICATION REPORT")


# Check all values are now numeric
non_numeric = X.select_dtypes(include=['object','category']).columns.tolist()
print(f"\n✅ Remaining non-numeric columns: {non_numeric or 'None — all encoded'}")

# Check train and test have same columns
train_cols = set(X.columns)
test_cols  = set(test_df.columns)
print(f"✅ Columns only in train: {train_cols - test_cols or 'None'}")
print(f"✅ Columns only in test:  {test_cols - train_cols or 'None'}")

# Check no nulls introduced
print(f"✅ Nulls in X:       {X.isnull().sum().sum()}")
print(f"✅ Nulls in test_df: {test_df.isnull().sum().sum()}")

# Show encoding mapping for each categorical
print(f"\n✅ Encoding mappings:")
for col, le in label_encoders.items():
    mapping = {cls: idx for idx, cls in enumerate(le.classes_)}
    print(f"   {col}: {mapping}")

# Final shapes
print(f"\n✅ Final X shape:       {X.shape}")
print(f"✅ Final test_df shape: {test_df.shape}")
print(f"✅ y shape:             {y.shape}")
print("Ready for feature engineering ✅")

from sklearn.model_selection import train_test_split

# ── Split ────────────────────────────────────────────────────────────
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"X_train: {X_train.shape} | X_valid: {X_valid.shape}")
print(f"y unique values: {y.nunique()} | min: {y.min():.4f} | max: {y.max():.4f}")

# ── Visualisation ────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle('Train / Validation Split', fontsize=13, fontweight='bold')

# Pie — split size
axes[0].pie([len(y_train), len(y_valid)],
            labels=[f'Train\n{len(y_train):,}', f'Valid\n{len(y_valid):,}'],
            colors=['steelblue','darkorange'],
            autopct='%1.1f%%', startangle=90)
axes[0].set_title('Split Size')

# Histogram — target distribution in train
axes[1].hist(y_train, bins=50, color='steelblue', edgecolor='white')
axes[1].set_title('Target Distribution — Train')
axes[1].set_xlabel('accident_risk')
axes[1].set_ylabel('Count')

# Histogram — target distribution in validation
axes[2].hist(y_valid, bins=50, color='darkorange', edgecolor='white')
axes[2].set_title('Target Distribution — Valid')
axes[2].set_xlabel('accident_risk')
axes[2].set_ylabel('Count')

plt.tight_layout()
plt.show()

import lightgbm as lgb
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# ── Evaluate function ─────────────────────────────────────────────────
def evaluate_model(model, X_train, y_train, X_valid, y_valid):
    model.fit(X_train, y_train)
    y_pred_train = model.predict(X_train)
    y_pred_valid = model.predict(X_valid)

    return {
        'Model':      model.__class__.__name__,
        'Train MAE':  round(mean_absolute_error(y_train, y_pred_train), 4),
        'Train RMSE': round(mean_squared_error(y_train, y_pred_train)**0.5, 4),
        'Train R2':   round(r2_score(y_train, y_pred_train), 4),
        'Valid MAE':  round(mean_absolute_error(y_valid, y_pred_valid), 4),
        'Valid RMSE': round(mean_squared_error(y_valid, y_pred_valid)**0.5, 4),
        'Valid R2':   round(r2_score(y_valid, y_pred_valid), 4),
        'Preds':      y_pred_valid
    }

# ── Run baseline models ───────────────────────────────────────────────
baseline_models = [
    LinearRegression(),
    Ridge(alpha=1.0),
    Lasso(alpha=0.01),
    ElasticNet(alpha=0.01, l1_ratio=0.5)
]

results_list = []
for model in baseline_models:
    r = evaluate_model(model, X_train, y_train, X_valid, y_valid)
    results_list.append(r)
    print(f"✅ {r['Model']:20} | Valid RMSE: {r['Valid RMSE']} | Valid R2: {r['Valid R2']}")

# ── LightGBM ──────────────────────────────────────────────────────────
lgb_model = lgb.LGBMRegressor(
    n_estimators      = 5000,
    learning_rate     = 0.01,
    num_leaves        = 31,
    min_child_samples = 20,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.1,
    reg_lambda        = 1.0,
    random_state      = 42,
    n_jobs            = -1
)

lgb_model.fit(
    X_train, y_train,
    eval_set  = [(X_valid, y_valid)],
    callbacks = [lgb.early_stopping(100), lgb.log_evaluation(500)]
)

y_pred_train_lgb = lgb_model.predict(X_train)
y_pred_valid_lgb = lgb_model.predict(X_valid)
y_pred_test      = lgb_model.predict(test_df)

lgb_result = {
    'Model':      'LightGBM',
    'Train MAE':  round(mean_absolute_error(y_train, y_pred_train_lgb), 4),
    'Train RMSE': round(mean_squared_error(y_train, y_pred_train_lgb)**0.5, 4),
    'Train R2':   round(r2_score(y_train, y_pred_train_lgb), 4),
    'Valid MAE':  round(mean_absolute_error(y_valid, y_pred_valid_lgb), 4),
    'Valid RMSE': round(mean_squared_error(y_valid, y_pred_valid_lgb)**0.5, 4),
    'Valid R2':   round(r2_score(y_valid, y_pred_valid_lgb), 4),
    'Preds':      y_pred_valid_lgb
}

results_list.append(lgb_result)
print(f"✅ {'LightGBM':20} | Valid RMSE: {lgb_result['Valid RMSE']} | Valid R2: {lgb_result['Valid R2']}")

# ── Results dataframe ─────────────────────────────────────────────────
results_df = pd.DataFrame([{k: v for k, v in r.items()
                             if k != 'Preds'}
                            for r in results_list])

print("\n" + "=" * 70)
print("                     MODEL COMPARISON TABLE")
print("=" * 70)
print(results_df[['Model','Train RMSE','Valid RMSE',
                   'Train R2','Valid R2','Valid MAE']].to_string(index=False))
print("=" * 70)
print(f"\n🏆 Best Valid RMSE : {results_df.loc[results_df['Valid RMSE'].idxmin(), 'Model']}")
print(f"🏆 Best Valid R2   : {results_df.loc[results_df['Valid R2'].idxmax(),   'Model']}")

colors = ['coral','coral','coral','coral','steelblue']  # LGB highlighted blue

fig, axes = plt.subplots(2, 3, figsize=(18, 11))
fig.suptitle('Baseline Models vs LightGBM', fontsize=14, fontweight='bold')

# ── 1. Valid RMSE comparison ──────────────────────────────────────────
ax = axes[0, 0]
bars = ax.bar(results_df['Model'], results_df['Valid RMSE'],
              color=colors, edgecolor='white')
ax.set_title('Valid RMSE (lower = better)')
ax.set_ylabel('RMSE')
ax.tick_params(axis='x', rotation=20)
for bar, val in zip(bars, results_df['Valid RMSE']):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.001,
            f'{val:.4f}', ha='center', fontsize=9)

# ── 2. Valid R2 comparison ────────────────────────────────────────────
ax = axes[0, 1]
bars = ax.bar(results_df['Model'], results_df['Valid R2'],
              color=colors, edgecolor='white')
ax.set_title('Valid R2 (higher = better)')
ax.set_ylabel('R2')
ax.tick_params(axis='x', rotation=20)
for bar, val in zip(bars, results_df['Valid R2']):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.001,
            f'{val:.4f}', ha='center', fontsize=9)

# ── 3. Valid MAE comparison ───────────────────────────────────────────
ax = axes[0, 2]
bars = ax.bar(results_df['Model'], results_df['Valid MAE'],
              color=colors, edgecolor='white')
ax.set_title('Valid MAE (lower = better)')
ax.set_ylabel('MAE')
ax.tick_params(axis='x', rotation=20)
for bar, val in zip(bars, results_df['Valid MAE']):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.001,
            f'{val:.4f}', ha='center', fontsize=9)

# ── 4. Actual vs Predicted — Linear Regression ───────────────────────
ax = axes[1, 0]
lr_preds = results_list[0]['Preds']
ax.scatter(y_valid, lr_preds, alpha=0.3, s=5, color='coral')
ax.plot([y_valid.min(), y_valid.max()],
        [y_valid.min(), y_valid.max()], 'r--', linewidth=1.5)
ax.set_title('Actual vs Predicted\nLinear Regression')
ax.set_xlabel('Actual')
ax.set_ylabel('Predicted')

# ── 5. Actual vs Predicted — LightGBM ────────────────────────────────
ax = axes[1, 1]
ax.scatter(y_valid, y_pred_valid_lgb, alpha=0.3, s=5, color='steelblue')
ax.plot([y_valid.min(), y_valid.max()],
        [y_valid.min(), y_valid.max()], 'r--', linewidth=1.5)
ax.set_title('Actual vs Predicted\nLightGBM')
ax.set_xlabel('Actual')
ax.set_ylabel('Predicted')

# ── 6. Feature importance — LightGBM ─────────────────────────────────
ax = axes[1, 2]
feat_imp = pd.Series(lgb_model.feature_importances_,
                     index=X_train.columns).sort_values(ascending=False).head(15)
feat_imp.plot(kind='barh', ax=ax, color='steelblue', edgecolor='white')
ax.invert_yaxis()
ax.set_title('Top 15 Feature Importances\nLightGBM')
ax.set_xlabel('Importance')

plt.tight_layout()
plt.show()

"""**Submission File **"""

# Redefine test_ids just in case
test_ids = pd.read_csv('/content/drive/MyDrive/playground-series-s5e10/test.csv')['id']

submission = pd.DataFrame({
    'id':            test_ids,                      # ← test_ids not test_df
    'accident_risk': np.clip(y_pred_test, 0, 1)
})

submission.to_csv('submission_lgbm.csv', index=False)

print(submission.head(10))
print(f"\nShape : {submission.shape}")
print(f"Min   : {submission['accident_risk'].min():.4f}")
print(f"Max   : {submission['accident_risk'].max():.4f}")
print(f"NaNs  : {submission['accident_risk'].isna().sum()}")
print("\n✅ submission_lgbm.csv ready to upload to Kaggle")